# -*- coding: utf-8 -*-
"""PPDM_ICA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z3lAHnZLHQf0BNsW8llGzyyOsBdJY3M0
"""

import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.decomposition import FastICA

x = pd.read_csv('/content/SonarSection.csv',sep=',')
originalData = pd.read_csv('/content/SonarOriginal.csv',sep=',')
x = x.select_dtypes(include='number')
originalData = originalData.select_dtypes(include='number')
x.head()

ica = FastICA(n_components=256,
              max_iter=500,
              random_state=1000)
perturbatedIca = ica.fit_transform(x)

output = originalData - perturbatedIca
coVariance = pd.DataFrame.cov(output)
finalResult = pd.DataFrame.sum(pd.DataFrame.sum(coVariance))
print(finalResult)