# -*- coding: utf-8 -*-
"""PPDM_AUC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gq2Q3u-ABVEDveovxg5CLdhUqYB3cRd_
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
dt=pd.read_csv('/content/SonarSection.csv',sep=',')
dt.head()

column_data = dt.columns
print(column_data)
#define the predictor variables and the response variable
X = dt[(column_data[0:len(column_data)-1])]

print(X)
y = dt[(column_data[len(column_data)-1])]
print(y)

#split the dataset into training (70%) and testing (30%) sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

#instantiate the model
log_regression = LogisticRegression()

#fit the model using the training data
log_regression.fit(X_train,y_train)

#use model to predict probability that given y value is 1
y_pred_proba = log_regression.predict_proba(X_test)[::,1]

#calculate AUC of model
auc = metrics.roc_auc_score(y_test, y_pred_proba)

#print AUC score
print(auc)

