# -*- coding: utf-8 -*-
"""Secracy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LooyxGUEZirDskoVxl3zqqBSmarGjd1Q
"""

import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.decomposition import FastICA

perturbData = pd.read_csv('/content/SonarSection.csv',sep=',')
originalData = pd.read_csv('/content/SonarOriginal.csv',sep=',')
perturbData = perturbData.select_dtypes(include='number')
originalData = originalData.select_dtypes(include='number')

SecurityRot = 0
numOFfeatures = originalData.columns

for k in numOFfeatures:
  variance = pd.DataFrame.var(originalData[k] - perturbData[k]) / pd.DataFrame.var(originalData[k])
  SecurityRot = SecurityRot + variance

secracy = SecurityRot/ len(numOFfeatures)
print(secracy)